### ISSUE TITLE
Implement 'yorm.match' utility

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/yorm#123]
The API could work something like:

```
return list(yorm.match(SampleModel, key='\w+'))
```

**Comment by jacebrowning** [comment]
@astronouth7303 Any thoughts on supporting regex patterns for matching? Would that be valuable or is `*` sufficient for most use cases?

**Comment by astronouth7303** [comment]
It's not valuable to my use case. I guess it depends on how rich of a querying system you want?

**Comment by jacebrowning** [comment]
Add in https://github.com/jacebrowning/yorm/pull/143

**Comment by jacebrowning** [comment]
This is available to start testing in `YORM==1.5b1`.
